package models

import "log"

var countryDialCodes = map[string][]string{
	"+93":  {"Afghanistan"},
	"+355": {"Albania"},
	"+213": {"Algeria"},
	"+1": {"United States", "Canada", "American Samoa", "Anguilla", "Antigua and Barbuda",
		"Bahamas", "Barbados", "Bermuda", "British Virgin Islands", "Cayman Islands",
		"Dominica", "Dominican Republic", "Grenada", "Guam", "Jamaica",
		"Montserrat", "Northern Mariana Islands", "Puerto Rico", "Saint Kitts and Nevis",
		"Saint Lucia", "Saint Vincent and the Grenadines", "Sint Maarten",
		"Trinidad and Tobago", "Turks and Caicos Islands", "US Virgin Islands"}, // Comprehensive NANP list
	"+376": {"Andorra"},
	"+244": {"Angola"},
	"+672": {"Antarctica", "Australian External Territories"}, // Shared with some Australian territories
	"+54":  {"Argentina"},
	"+374": {"Armenia"},
	"+297": {"Aruba"},
	"+247": {"Ascension Island"},
	"+61":  {"Australia", "Christmas Island", "Cocos (Keeling) Islands", "Norfolk Island"}, // Including external territories
	"+43":  {"Austria"},
	"+994": {"Azerbaijan"},
	"+973": {"Bahrain"},
	"+880": {"Bangladesh"},
	"+375": {"Belarus"},
	"+32":  {"Belgium"},
	"+501": {"Belize"},
	"+229": {"Benin"},
	"+975": {"Bhutan"},
	"+591": {"Bolivia"},
	"+387": {"Bosnia and Herzegovina"},
	"+267": {"Botswana"},
	"+55":  {"Brazil"},
	"+246": {"British Indian Ocean Territory"},
	"+673": {"Brunei"},
	"+359": {"Bulgaria"},
	"+226": {"Burkina Faso"},
	"+257": {"Burundi"},
	"+855": {"Cambodia"},
	"+237": {"Cameroon"},
	"+238": {"Cape Verde"},
	"+236": {"Central African Republic"},
	"+235": {"Chad"},
	"+56":  {"Chile"},
	"+86":  {"China"},
	"+57":  {"Colombia"},
	"+269": {"Comoros"},
	"+243": {"DR Congo"}, // Democratic Republic of the Congo
	"+242": {"Congo"},    // Republic of the Congo
	"+682": {"Cook Islands"},
	"+506": {"Costa Rica"},
	"+225": {"Côte d'Ivoire"},
	"+385": {"Croatia"},
	"+53":  {"Cuba"},
	"+599": {"Curaçao", "Caribbean Netherlands", "Sint Eustatius", "Saba"}, // Shared code for various Dutch Caribbean entities
	"+357": {"Cyprus"},
	"+420": {"Czech Republic"},
	"+45":  {"Denmark"},
	"+253": {"Djibouti"},
	"+670": {"East Timor (Timor-Leste)"},
	"+593": {"Ecuador"},
	"+20":  {"Egypt"},
	"+503": {"El Salvador"},
	"+240": {"Equatorial Guinea"},
	"+291": {"Eritrea"},
	"+372": {"Estonia"},
	"+268": {"Eswatini"}, // Formerly Swaziland
	"+251": {"Ethiopia"},
	"+500": {"Falkland Islands"},
	"+298": {"Faroe Islands"},
	"+679": {"Fiji"},
	"+358": {"Finland", "Åland Islands"}, // Åland is part of Finland
	"+33":  {"France"},
	"+594": {"French Guiana"},
	"+689": {"French Polynesia"},
	"+241": {"Gabon"},
	"+220": {"Gambia"},
	"+995": {"Georgia"},
	"+49":  {"Germany"},
	"+233": {"Ghana"},
	"+350": {"Gibraltar"},
	"+30":  {"Greece"},
	"+299": {"Greenland"},
	"+590": {"Guadeloupe", "Saint Barthélemy", "Saint Martin (French part)"}, // Shared code
	"+502": {"Guatemala"},
	"+44":  {"United Kingdom", "Guernsey", "Isle of Man", "Jersey"}, // UK and Crown Dependencies
	"+224": {"Guinea"},
	"+245": {"Guinea-Bissau"},
	"+592": {"Guyana"},
	"+509": {"Haiti"},
	"+504": {"Honduras"},
	"+852": {"Hong Kong"},
	"+36":  {"Hungary"},
	"+354": {"Iceland"},
	"+91":  {"India"},
	"+62":  {"Indonesia"},
	"+98":  {"Iran"},
	"+964": {"Iraq"},
	"+353": {"Ireland"},
	"+972": {"Israel"},
	"+39":  {"Italy", "Vatican City"}, // Vatican City uses Italy's code
	"+81":  {"Japan"},
	"+962": {"Jordan"},
	"+7":   {"Kazakhstan", "Russia"}, // Shared code
	"+254": {"Kenya"},
	"+686": {"Kiribati"},
	"+383": {"Kosovo"}, // Not universally recognized
	"+965": {"Kuwait"},
	"+996": {"Kyrgyzstan"},
	"+856": {"Laos"},
	"+371": {"Latvia"},
	"+961": {"Lebanon"},
	"+266": {"Lesotho"},
	"+231": {"Liberia"},
	"+218": {"Libya"},
	"+423": {"Liechtenstein"},
	"+370": {"Lithuania"},
	"+352": {"Luxembourg"},
	"+853": {"Macau"},
	"+261": {"Madagascar"},
	"+265": {"Malawi"},
	"+60":  {"Malaysia"},
	"+960": {"Maldives"},
	"+223": {"Mali"},
	"+356": {"Malta"},
	"+692": {"Marshall Islands"},
	"+596": {"Martinique"},
	"+222": {"Mauritania"},
	"+230": {"Mauritius"},
	"+262": {"Mayotte", "Réunion"}, // Shared code
	"+52":  {"Mexico"},
	"+691": {"Micronesia"},
	"+373": {"Moldova"},
	"+377": {"Monaco"},
	"+976": {"Mongolia"},
	"+382": {"Montenegro"},
	"+212": {"Morocco", "Western Sahara"}, // Western Sahara also uses Morocco's code
	"+258": {"Mozambique"},
	"+95":  {"Myanmar (Burma)"},
	"+264": {"Namibia"},
	"+674": {"Nauru"},
	"+977": {"Nepal"},
	"+31":  {"Netherlands"},
	"+687": {"New Caledonia"},
	"+64":  {"New Zealand"},
	"+505": {"Nicaragua"},
	"+227": {"Niger"},
	"+234": {"Nigeria"},
	"+683": {"Niue"},
	"+850": {"North Korea"},
	"+47":  {"Norway", "Svalbard and Jan Mayen"}, // Svalbard and Jan Mayen use Norway's code
	"+968": {"Oman"},
	"+92":  {"Pakistan"},
	"+680": {"Palau"},
	"+970": {"Palestine"},
	"+507": {"Panama"},
	"+675": {"Papua New Guinea"},
	"+595": {"Paraguay"},
	"+51":  {"Peru"},
	"+63":  {"Philippines"},
	"+870": {"Pitcairn Islands"}, // Satellite phone code
	"+48":  {"Poland"},
	"+351": {"Portugal"},
	"+974": {"Qatar"},
	"+40":  {"Romania"},
	"+250": {"Rwanda"},
	"+290": {"Saint Helena", "Tristan da Cunha"}, // Shared code for Saint Helena, Ascension, and Tristan da Cunha
	"+508": {"Saint Pierre and Miquelon"},
	"+685": {"Samoa"},
	"+378": {"San Marino"},
	"+239": {"Sao Tome and Principe"},
	"+966": {"Saudi Arabia"},
	"+221": {"Senegal"},
	"+381": {"Serbia"},
	"+248": {"Seychelles"},
	"+232": {"Sierra Leone"},
	"+65":  {"Singapore"},
	"+421": {"Slovakia"},
	"+386": {"Slovenia"},
	"+677": {"Solomon Islands"},
	"+252": {"Somalia"},
	"+27":  {"South Africa"},
	"+82":  {"South Korea"},
	"+211": {"South Sudan"},
	"+34":  {"Spain"},
	"+94":  {"Sri Lanka"},
	"+249": {"Sudan"},
	"+597": {"Suriname"},
	"+46":  {"Sweden"},
	"+41":  {"Switzerland"},
	"+963": {"Syria"},
	"+886": {"Taiwan"},
	"+992": {"Tajikistan"},
	"+255": {"Tanzania"},
	"+66":  {"Thailand"},
	"+228": {"Togo"},
	"+690": {"Tokelau"},
	"+676": {"Tonga"},
	"+216": {"Tunisia"},
	"+90":  {"Turkey"},
	"+993": {"Turkmenistan"},
	"+688": {"Tuvalu"},
	"+256": {"Uganda"},
	"+380": {"Ukraine"},
	"+971": {"United Arab Emirates"},
	"+598": {"Uruguay"},
	"+998": {"Uzbekistan"},
	"+678": {"Vanuatu"},
	"+58":  {"Venezuela"},
	"+84":  {"Vietnam"},
	"+681": {"Wallis and Futuna"},
	"+967": {"Yemen"},
	"+260": {"Zambia"},
	"+263": {"Zimbabwe"},
}

func IsCountryCodeCorrect(code string) bool {
	Country, err := countryDialCodes[code]
	log.Println("Country was", Country, err)
	if !err {
		return false
	}
	return true
}
